#!/usr/bin/env sh

set -e
set -o pipefail

./gradlew preparePublish
./gradlew publishAllPublicationsToSonatypeRepository closeAndReleaseSonatypeStagingRepository
./gradlew seskar-gradle-plugin:publishPlugins
./gradlew prepareDevelopment
